### ISSUE TITLE
Binary Clock improvement steps

### ISSUE THREAD

**Issue by chester1000** [chester1000/Pretty-Binary-Clock#12]
- [x] 0. Create issues for all steps in milestone 0.8,
- [x] 1. [#13] Simplify as much as possible for the latest API level,
- [x] 2. [#14] Gradually extend support down to APIs 10,
- [x] 3. [#15] Test stuff on real (old and new) devices,
- [x] 4. [#16] Add analytics to see what's being used,
- [ ] 5. Publish v0.8,
- [ ] 6. Add features (ex. Group=number, [Gray code](http://en.wikipedia.org/wiki/Gray_code), [Ternary](http://en.wikipedia.org/wiki/Ternary_numeral_system), etc...),
- [x] 7. [#17] Add Android Wear support,
- [x] 8. [#18] Add themes support (option for anyone to create themes?).
